server:
  port: 8081

spring:
  kafka:
    consumer:
      group-id: "default"

  datasource:
    url: jdbc:postgresql://localhost:5432/frame
    username: postgres
    password: password
  sql:
    init:
      mode: always

topic:
  name: frames
