server:
  port: 8081

spring:
  kafka:
    consumer:
      group-id: "default"

  datasource:
    url: jdbc:postgresql://localhost:5432/frame
    username: postgres
    password: password

topic:
  name: frames
